# Generated by Django 5.1.5 on 2025-01-25 23:55

from django.db import migrations

from makerschatbot.functions.read_sql_file import readsqlfile


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
            migrations.RunSQL(
            sql=readsqlfile('core/data/create_users'),  
            reverse_sql=readsqlfile('core/data/delete_users')  
        )
    ]