# Generated by Django 5.1.5 on 2025-01-26 16:15

from django.db import migrations

from makerschatbot.functions.read_sql_file import readsqlfile


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250126_1114'),
    ]

    operations = [
                migrations.RunSQL(
sql=readsqlfile('core/stakeholder/data/create_stakeholders'),  
reverse_sql=readsqlfile('core/stakeholder/data/delete_stakeholders')  
        )
    ]
