# Generated by Django 5.1.5 on 2025-01-26 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(db_comment='Identificador único para el chat.', primary_key=True, serialize=False, verbose_name='ID del Chat')),
                ('name', models.CharField(db_comment='Nombre o título descriptivo del chat.', max_length=255, verbose_name='Nombre del Chat')),
                ('created_by', models.ForeignKey(db_comment='Usuario que creó este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to='core.user', verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora de creación de este registro.', verbose_name='Creado en')),
                ('updated_by', models.ForeignKey(db_comment='Usuario que actualizó por última vez este registro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to='core.user', verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha y hora de la última actualización de este registro.', null=True, verbose_name='Actualizado en')),
                ('deleted_by', models.ForeignKey(db_comment='Usuario que realizó la eliminación lógica de este registro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to='core.user', verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Fecha y hora de la eliminación lógica de este registro.', null=True, verbose_name='Eliminado en')),
                ('audit_status', models.CharField(choices=[('C', 'Created'), ('U', 'Updated'), ('D', 'Deleted')], db_comment='Estado del registro (Creado, Actualizado, Eliminado).', default='C', max_length=1, verbose_name='Estado de Auditoría')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'db_table': '"chat"."chat"',
                'db_table_comment': 'Chat: almacena el título o cabecera de cada chat, el cual tiene relacionados múltiples detalles de interacción (ChatDetail).',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(db_comment='Unique identifier for the chat prompt', primary_key=True, serialize=False, verbose_name='Prompt ID')),
                ('prompt', models.TextField(db_comment="Full text of the user's input prompt", verbose_name='User Prompt')),
                ('chat', models.ForeignKey(db_comment='Chat conversation containing this prompt', on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='chat.chat', verbose_name='Associated Chat')),
                ('created_by', models.ForeignKey(db_comment='Usuario que creó este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to='core.user', verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora de creación de este registro.', verbose_name='Creado en')),
                ('updated_by', models.ForeignKey(db_comment='Usuario que actualizó por última vez este registro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to='core.user', verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha y hora de la última actualización de este registro.', null=True, verbose_name='Actualizado en')),
                ('deleted_by', models.ForeignKey(db_comment='Usuario que realizó la eliminación lógica de este registro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to='core.user', verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Fecha y hora de la eliminación lógica de este registro.', null=True, verbose_name='Eliminado en')),
                ('audit_status', models.CharField(choices=[('C', 'Created'), ('U', 'Updated'), ('D', 'Deleted')], db_comment='Estado del registro (Creado, Actualizado, Eliminado).', default='C', max_length=1, verbose_name='Estado de Auditoría')),
            ],
            options={
                'verbose_name': 'Chat Prompt',
                'verbose_name_plural': 'Chat Prompts',
                'db_table': '"chat"."prompt"',
                'db_table_comment': 'Stores all prompts and responses within chat conversations',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(db_comment='Unique identifier for the chat response', primary_key=True, serialize=False, verbose_name='Response ID')),
                ('prompt', models.ForeignKey(db_comment='Original user prompt that generated this response', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='chat.prompt', verbose_name='Related Prompt')),
                ('content', models.TextField(db_comment='Full text of the AI-generated response to the user', verbose_name='Chatbot Response')),
                ('rating', models.DecimalField(blank=True, db_comment='User-provided quality rating for the chatbot response. Decimal value between 0.00 (Very poor) and 100.00 (Excellent).', decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Minimum rating is 0.00 (Very poor)'), django.core.validators.MaxValueValidator(100.0, 'Maximum rating is 100.00 (Excellent)')], verbose_name='User Rating')),
            ],
            options={
                'verbose_name': 'Chat Response',
                'verbose_name_plural': 'Chat Responses',
                'db_table': '"chat"."response"',
                'db_table_comment': 'Stores chatbot responses and user ratings for quality analysis',
            },
        ),
    ]
