# Generated by Django 5.1.5 on 2025-01-25 23:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(db_comment='Identificador único para la conversación.', primary_key=True, serialize=False, verbose_name='ID de Conversación')),
                ('name', models.CharField(db_comment='Nombre o título descriptivo de la conversación.', max_length=255, verbose_name='Nombre de la Conversación')),
                ('created_by', models.ForeignKey(db_comment='Usuario que creó este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to='core.user', verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora de creación de este registro.', verbose_name='Creado en')),
                ('deleted_by', models.ForeignKey(db_comment='Usuario que realizó la eliminación lógica de este registro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to='core.user', verbose_name='Eliminado por')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha y hora de la última actualización de este registro.', null=True, verbose_name='Actualizado en')),
                ('updated_by', models.ForeignKey(db_comment='Usuario que actualizó por última vez este registro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to='core.user', verbose_name='Actualizado por')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Fecha y hora de la eliminación lógica de este registro.', null=True, verbose_name='Eliminado en')),
                ('audit_status', models.CharField(choices=[('C', 'Created'), ('U', 'Updated'), ('D', 'Deleted')], db_comment='Estado del registro (Creado, Actualizado, Eliminado).', default='C', max_length=1, verbose_name='Estado de Auditoría')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'db_table': '"chat"."conversation"',
                'db_table_comment': 'Conversación: almacena el título o cabecera de cada chat, el cual tiene relacionados múltiples detalles de conversación (ConversationDetail).',
            },
        ),
        migrations.CreateModel(
            name='ConversationDetail',
            fields=[
                ('id', models.UUIDField(db_comment='Identificador único para el detalle de conversación.', primary_key=True, serialize=False, verbose_name='ID del Detalle de Conversación')),
                ('Conversation', models.ForeignKey(db_comment='Cabecera de conversación asociada a este detalle.', on_delete=django.db.models.deletion.PROTECT, related_name='Conversation_details', to='chat.conversation', verbose_name='Cabecera de Conversación')),
                ('question', models.TextField(db_comment='Texto de la pregunta realizada.', verbose_name='Pregunta')),
                ('answer', models.TextField(db_comment='Texto de la respuesta proporcionada.', verbose_name='Respuesta')),
                ('rating', models.DecimalField(db_comment='Calificación proporcionada por el usuario para la respuesta del chatbot. Debe ser un valor decimal entre 0.00 (Muy mal) y 100.00 (Excelente).', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0, 'La calificación mínima es 0.00 (Muy mal)'), django.core.validators.MaxValueValidator(100.0, 'La calificación máxima es 100.00 (Excelente)')], verbose_name='Calificación del Chatbot')),
                ('created_by', models.ForeignKey(db_comment='Usuario que creó este registro.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to='core.user', verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora de creación de este registro.', verbose_name='Creado en')),
                ('updated_by', models.ForeignKey(db_comment='Usuario que actualizó por última vez este registro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to='core.user', verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha y hora de la última actualización de este registro.', null=True, verbose_name='Actualizado en')),
                ('deleted_by', models.ForeignKey(db_comment='Usuario que realizó la eliminación lógica de este registro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to='core.user', verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Fecha y hora de la eliminación lógica de este registro.', null=True, verbose_name='Eliminado en')),
                ('audit_status', models.CharField(choices=[('C', 'Created'), ('U', 'Updated'), ('D', 'Deleted')], db_comment='Estado del registro (Creado, Actualizado, Eliminado).', default='C', max_length=1, verbose_name='Estado de Auditoría')),
            ],
            options={
                'verbose_name': 'Detalle de Conversación',
                'verbose_name_plural': 'Detalles de Conversación',
                'db_table': '"chat"."conversation_detail"',
                'db_table_comment': 'Detalle del chat: registra el detalle de la conversación de cada chat',
            },
        ),
    ]
