# Generated by Django 5.1.5 on 2025-01-26 16:17

from django.db import migrations

from makerschatbot.functions.read_sql_file import readsqlfile


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        
                        migrations.RunSQL(
        sql=readsqlfile('inventory/brand/data/create_brands'),  
reverse_sql=readsqlfile('inventory/brand/data/delete_brands') 
        )
        

    ]
