# Generated by Django 5.1.5 on 2025-01-26 16:18

from django.db import migrations

from makerschatbot.functions.read_sql_file import readsqlfile


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20250126_1117'),
    ]

    operations = [
        
                                migrations.RunSQL(
       sql=readsqlfile('inventory/product_type/data/create'),  
reverse_sql=readsqlfile('inventory/product_type/data/create')  
        )
    ]
