# Generated by Django 5.1.5 on 2025-01-26 02:14

from django.db import migrations

from makerschatbot.functions.read_sql_file import readsqlfile


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20250125_1926'),
    ]

    operations = [
        
                        migrations.RunSQL(
            sql=readsqlfile('inventory/product_type/data/insert_product_type'),  
            reverse_sql=readsqlfile('inventory/product_type/data/delete_product_type')  
        )
    ]
