# Generated by Django 5.1.5 on 2025-01-26 16:26

from django.db import migrations

from makerschatbot.functions.read_sql_file import readsqlfile


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20250126_1118'),
    ]

    operations = [
        
                                        migrations.RunSQL(
sql=readsqlfile('inventory/tag/data/insert_tags'),  
reverse_sql=readsqlfile('inventory/tag/data/delete_tags') 
        ),
        migrations.RunSQL(
sql=readsqlfile('inventory/product/data/insert_product'),  
reverse_sql=readsqlfile('inventory/product/data/delete_product')  )
    ]
