# Generated by Django 5.1.5 on 2025-01-26 02:16

from django.db import migrations

from makerschatbot.functions.read_sql_file import readsqlfile


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20250125_2115'),
    ]

    operations = [
        
                                        migrations.RunSQL(
            sql=readsqlfile('inventory/product/data/insert_product'),  
            reverse_sql=readsqlfile('inventory/product/data/delete_product')  
        )
    ]
