# Generated by Django 5.1.5 on 2025-01-26 16:28

from django.db import migrations

from makerschatbot.functions.read_sql_file import readsqlfile


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20250126_1126'),
    ]

    operations = [
                migrations.RunSQL(
sql=readsqlfile('inventory/user_product/data/insert_user_product'),  
reverse_sql=readsqlfile('inventory/user_product/data/delete_user_product')   )
        
    ]
