# Generated by Django 5.1.5 on 2025-01-26 17:12

from django.db import migrations

from makerschatbot.functions.read_sql_file import readsqlfile


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20250126_1128'),
    ]

    operations = [
                        migrations.RunSQL(
sql=readsqlfile('inventory/inventory/data/insert'),  
reverse_sql=readsqlfile('inventory/inventory/data/insert')   )
    ]
