# Generated by Django 5.1.5 on 2025-01-26 17:36

from django.db import migrations

from makerschatbot.functions.read_sql_file import readsqlfile


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20250126_1212'),
    ]

    operations = [
                                migrations.RunSQL(
sql=readsqlfile('inventory/product_tag/data/insert_product_tag'),  
reverse_sql=readsqlfile('inventory/product_tag/data/delete_product_tag') )
    ]
